/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.amc.web.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2015
 * 
 * XDoclet definition:
 * @struts.form name="productForm"
 */
public class ProductForm extends ActionForm {
	private String pid;
	private String pname;
	private Float psize;
	private Float pweight;
	private Float psaleprice;
	private Float ppurchaseprice;
	private Integer pinventoryamount;
	private Integer psafeamount;
	public String getPid() {
		return pid;
	}
	public void setPid(String pid) {
		this.pid = pid;
	}
	public String getPname() {
		return pname;
	}
	public void setPname(String pname) {
		this.pname = pname;
	}
	public Float getPsize() {
		return psize;
	}
	public void setPsize(Float psize) {
		this.psize = psize;
	}
	public Float getPweight() {
		return pweight;
	}
	public void setPweight(Float pweight) {
		this.pweight = pweight;
	}
	public Float getPsaleprice() {
		return psaleprice;
	}
	public void setPsaleprice(Float psaleprice) {
		this.psaleprice = psaleprice;
	}
	public Float getPpurchaseprice() {
		return ppurchaseprice;
	}
	public void setPpurchaseprice(Float ppurchaseprice) {
		this.ppurchaseprice = ppurchaseprice;
	}
	public Integer getPinventoryamount() {
		return pinventoryamount;
	}
	public void setPinventoryamount(Integer pinventoryamount) {
		this.pinventoryamount = pinventoryamount;
	}
	public Integer getPsafeamount() {
		return psafeamount;
	}
	public void setPsafeamount(Integer psafeamount) {
		this.psafeamount = psafeamount;
	}
	
	
	
	
}