/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.amc.web.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-18-2015
 * 
 * XDoclet definition:
 * @struts.form name="supplierForm"
 */
public class SupplierForm extends ActionForm {
	private String sid;
	private String sname;
	private String scontactPerson;
	private String saddress;
	private String sphone;
	private String semail;
	public String getSid() {
		return sid;
	}
	public void setSid(String sid) {
		this.sid = sid;
	}
	public String getSname() {
		return sname;
	}
	public void setSname(String sname) {
		this.sname = sname;
	}
	public String getScontactPerson() {
		return scontactPerson;
	}
	public void setScontactPerson(String scontactPerson) {
		this.scontactPerson = scontactPerson;
	}
	public String getSaddress() {
		return saddress;
	}
	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}
	public String getSphone() {
		return sphone;
	}
	public void setSphone(String sphone) {
		this.sphone = sphone;
	}
	public String getSemail() {
		return semail;
	}
	public void setSemail(String semail) {
		this.semail = semail;
	}
	
	
}