/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.amc.web.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-12-2015
 * 
 * XDoclet definition:
 * @struts.form name="updatePwdForm"
 */
public class UpdatePwdForm extends ActionForm {
	private int uid;
	private String unowpassword;
	private String unewpassword;
	public int getUid() {
		return uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}
	public String getUnowpassword() {
		return unowpassword;
	}
	public void setUnowpassword(String unowpassword) {
		this.unowpassword = unowpassword;
	}
	public String getUnewpassword() {
		return unewpassword;
	}
	public void setUnewpassword(String unewpassword) {
		this.unewpassword = unewpassword;
	}
	
}