/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.amc.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.amc.domain.AmcUser;
import com.amc.service.UserService;
import com.amc.util.MDUtil;
import com.amc.web.form.LoginUserForm;

public class LoginAction extends DispatchAction {
	
	private UserService userService;
	
	public UserService getUserService() {
		return userService;
	}
	public void setUserService(UserService userService) {
		this.userService = userService;
	}


	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		LoginUserForm userForm=(LoginUserForm)form;
		String identity=(String) request.getSession().getAttribute("identity");
		if(identity.equalsIgnoreCase(userForm.getIdentity())){
			AmcUser user=new AmcUser();
			user.setName(userForm.getUsername());
			user.setPassword(MDUtil.md5Encode(userForm.getPassword()));
			
			user=userService.validateUser(user);
			
			if(user!=null){
				
				request.getSession().setAttribute("user", user);
				return mapping.findForward("ok");
			}
			return mapping.findForward("fail_pwd");
			
		}else{
			return mapping.findForward("fail_code");
		}
		
		
		
	}
	
	
}